# Site settings
name: Think Deep,Work Lean
author: brite
title: brite's blog
url: https://briteming.github.io/zgi 
baseurl: 
description: 爱生命爱折腾，从事互联网
meta_description: 逆水行舟，不进则退；取法乎上，仅得其中，取法乎中，仅得其下；究天人之际，通古今之变，成一家之言
motto: Think Deep,Work Lean
banner: 学而不思则罔，思而不学则殆。

permalink: /:year/:month/:day/:title/
paginate: 5

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: briteming

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


